name: Contribute a design
description: Use this form to make a design contribution (for example, new component idea, updates to an existing one).
title: "[Design]: "
labels: ["WG: Proposal", "Design"]

body:
  - type: markdown
    attributes:
      value: |
        **How to name this issue:** Please use the convention `[Action] [Component]` in the issue title above (e.g., "Add new variant to table", "Update breadcrumbs").
        
        ---

        Use this form to make a design contribution. You can contribute an idea for validation or submit a fully fledged design proposal for acceptance. For example:
        - Updates or changes to an existing component
        - A variant of an existing component
        - An idea for a new component you want to validate before starting work

        **An idea should have most of the following characteristics:**
        - **Unique** – Solves a problem not addressed by existing solutions in the Design System
        - **Useful** – Addresses a problem faced by multiple products or teams, not just a niche problem
        - **New** – Is not already listed in the [Vanilla backlog](/canonical/vanilla-framework/issues)
        - **Consistent** – Complies with all brand and design system guidelines
        - **Functional** – Provides clear accessibility or usability benefits beyond aesthetics

        **A fully fledged proposal should:**
        - Be flexible enough for multiple use cases
        - Consider how other designers might use the design in the future
        - Match the styles from the design foundations of the Design System (font scale, colors, spacing) 
        - Consider how accessibility will be taken into account
        - Include research
        - Include clear and detailed documentation

        Check our contributions process for more on how we triage ideas and proposals.

  - type: checkboxes
    id: existing-issue-check
    attributes:
      label: Check if there’s an existing issue about this design
      description: "Please [search the existing issues](/canonical/vanilla-framework/issues) to see if this has been discussed before."
      options:
        - label: I have searched the existing issues and this is new.
          required: true

  - type: textarea
    id: design-contribution
    attributes:
      label: Tell us about your design contribution
      description: "What’s the design you want to contribute and why? Please describe the component, update, or idea and the problem it solves. You can also add links and upload images to prototypes or screenshots of your contribution."
    validations:
      required: true

  - type: textarea
    id: usage-context
    attributes:
      label: When should we use your contribution?
      description: "Give us some context and scenarios for using your contribution."

  - type: textarea
    id: accessibility
    attributes:
      label: How is your contribution accessible?
      description: "Explain what considerations have you made to comply with [accessibility standards](https://vanillaframework.io/accessibility)."
